apiVersion: v1
kind: Service
metadata:
  name: {{ include "aqua-os.fullname" . }}-web
  labels:
    {{- include "aqua-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
      protocol: TCP
  selector:
    {{- include "aqua-os.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
