apiVersion: v1
kind: Service
metadata:
  name: {{ include "aqua-os.fullname" . }}-crew
  labels:
    {{- include "aqua-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: crew
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.crew.service.port }}
      targetPort: {{ .Values.crew.service.port }}
      protocol: TCP
  selector:
    {{- include "aqua-os.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: crew
